### PR TITLE
Conventional commits

### PR DESCRIPTION
**Pull request by ngonzalezpazFC**

### CODE REVIEW

**Review by javier-godoy — CHANGES_REQUESTED** [review]
412d094 commits PR #7 which implements a feature. Should be `feat`

**Comment by ngonzalezpazFC** [comment]
> 
> 
> [412d094](https://github.com/FlowingCode/GoogleMapsAddon/commit/412d094fb5d3af34ed5ea9cf4c15900d8f3722a7) commits PR #7 which implements a feature. Should be `feat`

Done

**Review by javier-godoy — CHANGES_REQUESTED** [review]
822b9ad the change to assembly.xml should either be in 1d6f711 or as a separate commit
67f3a36 closes `#6`

**Comment by javier-godoy** [comment]
@ngonzalezpazFC Please cherry pick #16 into this

**Comment by ngonzalezpazFC** [comment]
> 
> 
> @ngonzalezpazFC Please cherry pick #16 into this

Done

**Comment by javier-godoy** [comment]
Reviewed (convention 1.0.0-SNAPSHOT.20201130) ✔

**Comment by javier-godoy** [comment]
@ngonzalezpazFC Please review

**Comment by ngonzalezpazFC** [comment]
> 
> 
> @ngonzalezpazFC Please review

Why are [94d70a0](https://github.com/FlowingCode/GoogleMapsAddon/pull/15/commits/94d70a0553fc00a8ddc58caa373621b5fe98094d) and [681f710](https://github.com/FlowingCode/GoogleMapsAddon/pull/15/commits/681f71025bebc32cf87414efaa6155bfabe9bfd5) feat type? I'm not sure that the changes include features the user could use.

**Comment by javier-godoy** [comment]
> > @ngonzalezpazFC Please review
> 
> Why are [94d70a0](https://github.com/FlowingCode/GoogleMapsAddon/pull/15/commits/94d70a0553fc00a8ddc58caa373621b5fe98094d) and [681f710](https://github.com/FlowingCode/GoogleMapsAddon/pull/15/commits/681f71025bebc32cf87414efaa6155bfabe9bfd5) feat type? I'm not sure that the changes include features the user could use.

They aren't `feat` to me either, but @mlopezFC mentioned that `test` is for "adding missing tests or refactoring/fixing existing tests" which isn't the case. In that sense, `feat(demo)` would be "adding a new feature in the demo scope".  I'll ask him to review in order to clarify that issue.

**Comment by mlopezFC** [comment]
> > > @ngonzalezpazFC Please review
> > 
> > 
> > Why are [94d70a0](https://github.com/FlowingCode/GoogleMapsAddon/pull/15/commits/94d70a0553fc00a8ddc58caa373621b5fe98094d) and [681f710](https://github.com/FlowingCode/GoogleMapsAddon/pull/15/commits/681f71025bebc32cf87414efaa6155bfabe9bfd5) feat type? I'm not sure that the changes include features the user could use.
> 
> They aren't `feat` to me either, but @mlopezFC mentioned that `test` is for "adding missing tests or refactoring/fixing existing tests" which isn't the case. In that sense, `feat(demo)` would be "adding a new feature in the demo scope". I'll ask him to review in order to clarify that issue.

If we consider that the user of this, is a dependent project that is using the demos, then it's a new feature for it.
[94d70a0](https://github.com/FlowingCode/GoogleMapsAddon/pull/15/commits/94d70a0553fc00a8ddc58caa373621b5fe98094d) if applied will add the feature of using the demo layout that will enable the demos project to show the demo properly
The same applies to [681f710](https://github.com/FlowingCode/GoogleMapsAddon/pull/15/commits/681f71025bebc32cf87414efaa6155bfabe9bfd5), but it could also be refactor, given that the same code is now in a central library.
A project can generate several artifacts that are consumed by different "users" or dependant projects. The demo project (that uses the demo artifacts generated from this one) is a separated project that has its own lifecycle involving production releases and everything, so this project is generating an artifact that is going to be used on production.
I think that the confusing thing here is that these artifacts are in the test folder. A further improvement would be to move demos to a src/demo folder instead of using src/test for that.

**Review by mlopezFC — APPROVED** [review]
LGTM

**Pull request merged**
